XMOJ-Script-dev/XMOJ-Script

.github/workflows/AutoLabelIssue.yml
=> fix AutoLabelIssue.yml

.github/workflows/UpdateVersion.yml, Update.json
=> fix permissions

XMOJ.user.js
=> use api.xmoj-bbs.tech

Update.json, XMOJ.user.js
=> 不自动提交已AC题目

Update.json, XMOJ.user.js
* Update XMOJ.user.js
* Update version info to 1.0.222
---------
=> Update XMOJ.user.js (#135)

Update.json, XMOJ.user.js
=> 修复部分题目状态页没有运行编号

AddonScript.js, Update.json, XMOJ.user.js
1.修改了大量中文 2.写明提醒内容 3.update 关键字词替换
=> 1.修改了大量中文 2.写明提醒内容 3.update 关键字词替换

Server/Source/Process.ts
Reverts XMOJ-Script-dev/XMOJ-Script#187
=> Revert "Update Process.ts"

Update.json, XMOJ.user.js
@langningchen What does this do besides cause console errors?
=> remove this as it causes console errors

Update.json, Update/UpdateVersion.js
Reverts XMOJ-Script-dev/XMOJ-Script#219
=> Revert "remove safety features...."

.github/workflows/Prerelease.yml
Reverts XMOJ-Script-dev/XMOJ-Script#218
=> Revert "Update Prerelease.yml"

Update.json, XMOJ.user.js
=> manual UpdateToRelease

Update.json, XMOJ.user.js
Reverts XMOJ-Script-dev/XMOJ-Script#239
=> Revert "manual UpdateToRelease"

.github/workflows/AutoLabelIssue.yml, .github/workflows/AutoLablePR.yml, .github/workflows/Daily.yml, .github/workflows/Prerelease.yml, .github/workflows/Release.yml, .github/workflows/UpdateVersion.yml
=> use github apps

.github/workflows/UpdateToRelease.yml
=> github app

.gitmodules
=> use submodule

.github/workflows/UpdateToRelease.yml
Reverts XMOJ-Script-dev/XMOJ-Script#243
fixes #266 for now
=> Revert "github app"

Update.json, XMOJ.user.js
=> send extra information

Update.json, XMOJ.user.js
=> use https in xmoj

.github/workflows/AutoLablePR.yml
Reverts XMOJ-Script-dev/XMOJ-Script#289
=> Revert "Bump actions/labeler from 4 to 5"

.github/workflows/Daily.yml
Reverts XMOJ-Script-dev/XMOJ-Script#290
=> Revert "Bump actions/stale from 8 to 9"

Update/UpdateToRelease.js, Update/UpdateVersion.js
=> A Small fix

Update.json, XMOJ.user.js, package.json
https://www.xmoj.tech/contest.php?cid=6659
=> Add an Easter egg

Update.json, XMOJ.user.js, package.json
=> fix release notes

.github/workflows/Prerelease.yml, .github/workflows/Release.yml
=> Update npm publish command to include provenance

Update.json, XMOJ.user.js, package.json
=> 修复无法在某些页面检查登录状态

Update.json
=> update rel notes

AddonScript.js
=> Add new year greetings

Update.json, XMOJ.user.js, package.json
=> add the native link

.github/workflows/Daily.yml, Update.json
=> 😉更改stale标准

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> add spellcheck

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> sleep for a sec after submitting to prevent xmoj from crashing

README.md
=> 增加赞助option

.github/workflows/sitemap-automation.yml, README.md
=> Python small q patch 1

Update.json, XMOJ.user.js, package.json
=> 更新support链接

Update.json, XMOJ.user.js, package.json
=> 修正部分用户姓名设置的错误

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> major restructuring(fixes #364)

Update.json, XMOJ.user.js, package.json
=> 增加更新链接，优化格式

Update.json, XMOJ.user.js, package.json
Reverts XMOJ-Script-dev/XMOJ-Script#424
why did you fmt...
tldr, use https://www.jetbrains.com/webstorm/
=> Revert "增加更新链接，优化格式"

Update.json, XMOJ.user.js, package.json
=> 增加开发组成员，zhouyiqing

Update.json, XMOJ.user.js, package.json
This fixes #433 
Popper.js is so stupid...
I understand and agree that this project and the …
=> fix  [Bug] 右上角用户名点击后无反应 

.github/workflows/sitemap-automation.yml, .idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> fix the unpkg-cdn option

.github/workflows/sitemap-automation.yml, .idea/vcs.xml, Update.json, XMOJ.user.js, package.json
=> regression!

XMOJ.user.js
Reverts XMOJ-Script-dev/XMOJ-Script#459
=> Revert "Update XMOJ.user.js"

Update.json, XMOJ.user.js, package.json
允许下载VMware Workstation Pro
允许下载Microsoft Visual Studio
~~允许管理员用户直接获取标程~~
I understand and agree …
=> 新增下载项并且允许管理员用户直接获取标程

Update.json, XMOJ.user.js, package.json
Reverts XMOJ-Script-dev/XMOJ-Script#478
=> Revert "Update to release 1.1.48"

Update.json, XMOJ.user.js, package.json
Reverts XMOJ-Script-dev/XMOJ-Script#476
=> Revert "新增下载项并且允许管理员用户直接获取标程"

.idea/workspace.xml, Update.json, XMOJ.user.js
=> and I am so frustrated I actually make another code contribution

Update.json, XMOJ.user.js, package.json
=> Update ticket email

.idea/.gitignore, .idea/XMOJ-Script.iml, .idea/modules.xml, .idea/workspace.xml, Update.json, XMOJ.user.js, package.json
- **make dismissing actually work**
- **remove not-cached**
@PythonSmall-Q review and merge!!!
=> Make the dismiss button work + improve showsource

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> move the main msg content into a div with flex!!! :tada:

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> add markdown support to short messages 

.idea/workspace.xml, Update.json, XMOJ.user.js, package.json
=> 让 ctrl + enter 触发自动提交当年代码

.github/workflows/similar-issue.yml
=> 增加silimar issue推送

Update.json, XMOJ.user.js, package.json
=> 支持跳转到讨论编号 修改讨论区用户界面 在讨论区Page过大时自动跳转 在讨论区最后一页自动删除

Update.json, XMOJ.user.js, package.json
=> 允许管理在用户页管理badge并在修改badge后清除缓存

Update.json, XMOJ.user.js, package.json
=> revert #514

Update.json, XMOJ.user.js, package.json
=> Auto Read Short message mentions

Update.json, XMOJ.user.js, package.json
=> Refresh Short Messages at fixed intervals (experimental)

Update.json, XMOJ.user.js, package.json
=> chore: 删除被 @boomzero 除名的开发组成员

Update.json, XMOJ.user.js, package.json
=> Revert Refresh Short Messages at fixed intervals (experimental)

index.html
=> MS Clarity

README.md
=> Product Hunt

Update.json, XMOJ.user.js, package.json
=> fix https://www.xmoj.tech/open_contest_sign_up.php

Update.json, XMOJ.user.js, package.json
=> Improve debug mode

Update.json, XMOJ.user.js, package.json
=> Update the api domain

Update.json, XMOJ.user.js, package.json
=> add username rendering for noticeboard

Update.json, XMOJ.user.js, package.json
Does not seem to do anything, @langningchen ?
Fixes #48
=> disable tidytable

Update.json, XMOJ.user.js, package.json
=> Upgrade bootstrap + cdnjs

Update.json, XMOJ.user.js, package.json
=> fix tidytable

Update.json, XMOJ.user.js, package.json
=> Improve popover usability

Update.json, XMOJ.user.js, package.json
=> fix copymd

Update.json, XMOJ.user.js, package.json
=> fix ACM rank

Update.json, XMOJ.user.js, package.json
Reverts XMOJ-Script-dev/XMOJ-Script#593
=> Revert "Extern contrib from @zhouyiqing"

XMOJ.user.js
=> 保证正常更新的新导航栏

Update.json, XMOJ.user.js, package.json
#46
There is certainly more work to be done, though
=> add some document.titles

Update.json, XMOJ.user.js, package.json
=> more document titles

.github/workflows/sync-to-extern-contrib.yml
=> Auto Sync to Extern contrib

Update.json, XMOJ.user.js, package.json
=> 美化导航栏（by zhouyiqing）

.github/pull_request_template.md, CONTRIBUTING.md
=> Write CONTRIBUTING.md

XMOJ.user.js
Please read the comments below to help us consider your Pull Request.
We are all volunteers and completing the process outlined will help us review your commits quicker.
Please use this pull request template, or your pull request will be closed.
**Please make sure you**
1. Base your code and PRs against the repositories developmental branch.
---
---
2. I have commented my proposed changes within the code and I …
=> 深色模式调整题目图片颜色

Update.json, XMOJ.user.js, package.json
Sync Extern Contrib from @zhouyiqing0304
Dunno, ask him. I'm just a bot beep-boop.
---
5. I have squashed any insignificant …
=> Extern contrib from @zhouyiqing0304

Update.json, XMOJ.user.js, package.json
Temp fix for #627 
Removes a problematic feature.
---
5. I have squashed any insignificant commits. ([`git …
=> Emergency fix

Update.json, XMOJ.user.js, package.json
The PR template did not render.
I accept the PR template.
=> Add error Reporting

XMOJ.user.js
哈哈哈不用谢
Please read the comments below to help us consider your Pull Request.
We are all volunteers and completing the process outlined will help us review your commits quicker.
Please use this pull request template, or your pull request will be closed.
**Please make sure you**
1. Base your code and PRs against the repositories developmental branch.
---
---
2. I have commented my proposed changes within the code …
=> 新增复制freopen语句功能，优化深色模式错误警告颜色显示

Update.json, XMOJ.user.js, package.json
One error shouldn't break everything.
---
Better error Reporting
wrap a try...catch around everything
---
5. I have …
=> Better error Reporting

Update.json, XMOJ.user.js, package.json
simple
---
5. I have squashed any insignificant commits. ([`git …
=> Codemirror for freopen

Update.json, XMOJ.user.js, package.json
=> format freopen statement

Update.json, XMOJ.user.js, package.json
=> prevent RE

Update.json, XMOJ.user.js, package.json
If you're curious, this is added to assist debugging. 
---
6. I have …
=> log Success

Update.json, XMOJ.user.js, package.json
error reporting for image upload
---
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase …
=> error reporting for image upload

Update.json, XMOJ.user.js, package.json
=> new toolbar item

Update.json, XMOJ.user.js, package.json
=> fix reply infinite looping

Update.json, XMOJ.user.js, package.json
=> fix replying

AddonScript.js, Update.json, XMOJ.user.js, package.json
=> fix replying(again)

Update.json, XMOJ.user.js, package.json
=> smartAlert!

Update.json, XMOJ.user.js, package.json
=> 允许在已结束的比赛下提交 #287

Update.json, XMOJ.user.js, package.json
---
6. I have checked that another pull request for this purpose does …
=> Remove headers

XMOJ.user.js
Please read the comments below to help us consider your Pull Request.
We are all volunteers and completing the process outlined will help us review your commits quicker.
Please use this pull request template, or your pull request will be closed.
**Please make sure you**
1. Base your code and PRs against the repositories developmental branch.
---
---
2. I have commented my proposed changes within the code and I …
=> 解决强制O2提交的问题

Update.json, XMOJ.user.js, package.json
=> Set turnstile theme and language

Update.json, XMOJ.user.js, package.json
Add CP Editor Download
Adding the link
---
5. I have squashed any insignificant commits. ([`git …
=> Add CP Editor

Update.json, XMOJ.user.js, package.json
add a new name
trivial
---
5. I have squashed any insignificant commits. ([`git …
=> add chenyiming5

Update.json, XMOJ.user.js, package.json
进入讨论后给出题目的链接 (fix #123)
* [`XMOJ.user.js`](diffhunk://#diff-dcd5dc88c3abdd0865e670a1d7e89a20c8d58bb15c59e095257105782de0a494L4850-R4850): Modified the `PostTitle` element to use `innerHTML` instead of `innerText`, and added an anchor tag around the problem ID to make it a clickable link that directs to the problem's page.
--- …
=> 进入讨论后给出题目的链接 

Update.json, XMOJ.user.js, package.json
Remove the statistics button from the contest page
idk, too hard for my understanding
---
5. I have squashed any …
=> Remove the statistics button from contest page

Update.json, XMOJ.user.js, package.json
Update diff-match-patch library source URL
Update diff-match-patch library source URL
---
5. I have squashed any …
=> Update diff-match-patch library source URL

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/feature.yml
6. I have checked that another pull request for this purpose does …
=> Add issue types for issue templates

Update.json, XMOJ.user.js, package.json
Fix the submit button on some pages
`lastChild` -> `lastElementChild`
---
5. I have squashed any insignificant commits. …
=> Fix the submit button on some pages
